version: "3.8"

services:
  mb-kosmetik:
    build:
      context: .
      dockerfile: Dockerfile
    image: mb-kosmetik:latest
    container_name: mb-kosmetik
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped